[project]
name = "pythonode"
version = "0.1.0"
description = "Embed Node.js natively in your Python code."
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "0880880"}]
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"