name: Build 

on:
  workflow_call:


jobs:
  build:
    name: Build shared libraries
    runs-on: ${{matrix.os}}

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64] 
        py: ['3.9', '3.10', '3.11', '3.12']
        versions: [v23.11.0]

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Install SConstruct
        run: pip install scons

      - name: Update setuptools, pip, and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Clone node repo
        run: git clone https://github.com/nodejs/node --depth 1 --branch ${{ matrix.versions }} nodejs
        env:
          GIT_TERMINAL_PROMPT: 0

      - name: Move necessery items to lib
        run: |
          mkdir -p pythonodejs/externals
          mv nodejs/deps/uv pythonodejs/externals/uv
          mv nodejs/deps/v8 pythonodejs/externals/v8
          mv nodejs/src pythonodejs/externals/node

      - name: Build binary
        run: scons

      - name: Validate Build Environment
        run: python setup.py check
      
      - name: Build wheels
        run: |
          pip install cibuildwheel
          cibuildwheel

      - name: Upload Binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pythonode-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.versions }}-${{ matrix.py }}
          path: wheelhouse/
