name:  Continuous Deployment (CD)

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:

  build:
    name: Build Project
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    
