name: Formatting Check

on:
  push:
    paths:
      - 'pythonodejs.cpp'
      - 'pythonodejs.h'
      - '**/*.py'
  pull_request:
    paths:
      - 'pythonodejs.cpp'
      - 'pythonodejs.h'
      - '**/*.py'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          if ! clang-format --dry-run --Werror pythonodejs.cpp pythonodejs.h; then
            echo "C/C++ code is not formatted properly."
            exit 1
          fi

  python-formatting:
    runs-on: ubuntu-latest
    needs: clang-format
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run code formatting check (Black)
        run: |
          if ! black --check --diff .; then
            echo "Code is not formatted according to Black."
            exit 1
          fi

      - name: Run custom import checks
        run: |
          find . -name '*.py' -not -path './.venv/*' -print0 |
          xargs -0 -n1 python check_imports.py